[package]
name = "urlcat"
version = "0.1.0"
edition = "2021"
authors = ["Tronikel <contactdonatas@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "2.1.2"
