name: Test

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: rust-toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: cargo test
              run: cargo test
